
(()=>{
const $=id=>document.getElementById(id), src=$("srcCanvas"), ov=$("overlayCanvas"), dst=$("dstCanvas");
const sctx=src.getContext("2d"), octx=ov.getContext("2d"); let img=null,file=null,pts=[],drag=-1,blob=null,text="";
function def(){const w=src.width,h=src.height,m=Math.max(15,Math.min(w,h)*.035);pts=[{x:m,y:m},{x:w-m,y:m},{x:w-m,y:h-m},{x:m,y:h-m}];draw();}
function draw(){ov.width=src.width;ov.height=src.height;octx.clearRect(0,0,ov.width,ov.height);if(pts.length!==4)return;octx.strokeStyle="#e2c35e";octx.fillStyle="rgba(255,255,255,.08)";octx.lineWidth=Math.max(3,src.width/300);octx.beginPath();octx.moveTo(pts[0].x,pts[0].y);pts.slice(1).forEach(p=>octx.lineTo(p.x,p.y));octx.closePath();octx.fill();octx.stroke();pts.forEach((p,i)=>{octx.beginPath();octx.arc(p.x,p.y,Math.max(10,src.width/60),0,Math.PI*2);octx.fillStyle="#fff";octx.fill();octx.strokeStyle="#173548";octx.stroke();octx.fillStyle="#173548";octx.font=`bold ${Math.max(12,src.width/50)}px sans-serif`;octx.textAlign="center";octx.textBaseline="middle";octx.fillText(i+1,p.x,p.y);});}
function pos(e){const r=ov.getBoundingClientRect();return{x:(e.clientX-r.left)*ov.width/r.width,y:(e.clientY-r.top)*ov.height/r.height};}
ov.onpointerdown=e=>{const p=pos(e);let best=-1,bd=1e9;pts.forEach((q,i)=>{const d=Math.hypot(p.x-q.x,p.y-q.y);if(d<bd){bd=d;best=i}});if(bd<80){drag=best;ov.setPointerCapture(e.pointerId)}};
ov.onpointermove=e=>{if(drag<0)return;const p=pos(e);pts[drag]={x:Math.max(0,Math.min(ov.width,p.x)),y:Math.max(0,Math.min(ov.height,p.y))};draw()};ov.onpointerup=()=>drag=-1;
$("scanFile").onchange=e=>{file=e.target.files[0];if(!file)return;const im=new Image();im.onload=()=>{img=im;const scale=Math.min(1,1400/Math.max(im.naturalWidth,im.naturalHeight));src.width=Math.round(im.naturalWidth*scale);src.height=Math.round(im.naturalHeight*scale);src.style.width="100%";sctx.drawImage(im,0,0,src.width,src.height);def();setTimeout(auto,100)};im.src=URL.createObjectURL(file)};
function sort(a){const sum=a.map(p=>p.x+p.y),dif=a.map(p=>p.x-p.y);return[a[sum.indexOf(Math.min(...sum))],a[dif.indexOf(Math.max(...dif))],a[sum.indexOf(Math.max(...sum))],a[dif.indexOf(Math.min(...dif))]]}
function auto(){if(!window.cv||!cv.Mat||!img)return;let a,b,c,e,cont,h;try{a=cv.imread(src);b=new cv.Mat();c=new cv.Mat();e=new cv.Mat();cont=new cv.MatVector();h=new cv.Mat();cv.cvtColor(a,b,cv.COLOR_RGBA2GRAY);cv.GaussianBlur(b,c,new cv.Size(5,5),0);cv.Canny(c,e,55,165);cv.findContours(e,cont,h,cv.RETR_LIST,cv.CHAIN_APPROX_SIMPLE);let best=null,area=0;for(let i=0;i<cont.size();i++){const x=cont.get(i),ap=new cv.Mat();cv.approxPolyDP(x,ap,.02*cv.arcLength(x,true),true);const ar=Math.abs(cv.contourArea(ap));if(ap.rows===4&&ar>src.width*src.height*.15&&ar>area){best=[];for(let r=0;r<4;r++)best.push({x:ap.intPtr(r,0)[0],y:ap.intPtr(r,0)[1]});area=ar}ap.delete();x.delete()}if(best){pts=sort(best);draw();$("ocrStatus").textContent="Bordes detectados. Puedes ajustar los puntos."}}catch(err){console.error(err)}finally{[a,b,c,e,h].forEach(x=>{try{x&&x.delete()}catch{}});try{cont&&cont.delete()}catch{}}}
$("autoEdges").onclick=auto;
$("perspective").onclick=()=>{if(!window.cv||pts.length!==4)return;const p=sort(pts),d=(x,y)=>Math.hypot(x.x-y.x,x.y-y.y),w=Math.round(Math.max(d(p[0],p[1]),d(p[3],p[2]))),h=Math.round(Math.max(d(p[0],p[3]),d(p[1],p[2])));let a,M,out;try{a=cv.imread(src);const sp=cv.matFromArray(4,1,cv.CV_32FC2,[p[0].x,p[0].y,p[1].x,p[1].y,p[2].x,p[2].y,p[3].x,p[3].y]),dp=cv.matFromArray(4,1,cv.CV_32FC2,[0,0,w-1,0,w-1,h-1,0,h-1]);M=cv.getPerspectiveTransform(sp,dp);out=new cv.Mat();cv.warpPerspective(a,out,M,new cv.Size(w,h),cv.INTER_CUBIC,cv.BORDER_REPLICATE,new cv.Scalar());dst.width=w;dst.height=h;cv.imshow(dst,out);dst.toBlob(b=>{blob=b;$("ocrBtn").disabled=!b;$("ocrStatus").textContent="Perspectiva corregida. Listo para OCR."},"image/jpeg",.93);sp.delete();dp.delete()}finally{[a,M,out].forEach(x=>{try{x&&x.delete()}catch{}})}};
$("ocrBtn").onclick=async()=>{if(!blob)return;$("ocrStatus").textContent="Leyendo ticket…";try{const r=await Tesseract.recognize(blob,"spa+eng",{logger:m=>{if(m.progress)$("ocrStatus").textContent=`OCR ${Math.round(m.progress*100)}%`}});text=r.data.text||"";const sug=parse(text);window.gasto360Cloud.setScan({original:file,corrected:blob,text});window.gasto360Cloud.fill(sug);$("ocrStatus").textContent="OCR completado. Revisa antes de guardar."}catch(e){console.error(e);window.gasto360Cloud.setScan({original:file,corrected:blob,text:""});window.gasto360Cloud.openExpense();}};
function parse(t){const lines=t.split(/\r?\n/).map(x=>x.trim()).filter(Boolean);let merchant=lines.find(x=>/[A-Za-zÁÉÍÓÚÑáéíóúñ]/.test(x)&&x.length>2)||"";let date="";let m=t.match(/\b(\d{2})[\/.-](\d{2})[\/.-](20\d{2})\b/);if(m)date=`${m[3]}-${m[2]}-${m[1]}`;const nums=[...t.matchAll(/(?<!\d)(\d{1,6}[.,]\d{2})(?:\s*€|\s*EUR)?/gi)].map(x=>Number(x[1].replace(",","."))).filter(x=>isFinite(x)&&x<100000);let amount=nums.length?Math.max(...nums):"";return{merchant,date:date||new Date().toISOString().slice(0,10),amount};}
})();
